### ISSUE TITLE
Invalid arguments on commands

### ISSUE THREAD

**Issue by dotkitkat** [pyraxo/sylphy#14]
![args1](https://cloud.githubusercontent.com/assets/26789415/24833575/6df752ee-1d21-11e7-9df6-d492a3719316.png)
I wrote an example `ping` command that takes a `member` as an input:
https://paste.safe.moe/xitikemiti.js
But I get the above image as an error when I don't specify a member. I think it has something to do with the fact that I don't have any i18n setup. I can't find anything on the wiki about i18n nor can I find any bots with an example.
**Also, when I do specify a member, trying to access any Eris properties like `.mention` comes up as `undefined.`**

**Comment by dotkitkat** [comment]
After finally searching around, I found that Yui had some locales. However, [when I make my own](https://hastebin.com/hubufusohi.json) and load them, all the strings load and work, except for INSUFFICIENT_ARGS. I have checked every one, making adjustments to ON_COOLDOWN and it did reflect in the bot, but INSUFFICIENT_ARGS still came up with the above error message.
This also happens with `member.NOT_FOUND`, using [this locale config.](https://paste.safe.moe/zifotowafe.json)

Is there any documentation, anywhere, on locales? Maybe even just an example of all locale options? I feel like I'm missing something.

**Comment by pyraxo** [comment]
strange. will look into it asap.

thanks for the heads up!

what's the response of INSUFFICIENT_ARGS? is it the same as the first message? @dotkitkat

**Comment by pyraxo** [comment]
@dotkitkat does your file directory look something like this:
```js
locales
  - en
    - default.json
    - anotherfile.json
  - jp
    - default.json
main.js
```
the locale folder should contain folders which are named after the locale, that contain json files

EDIT: whoops, never mind, was missing dem curly braces
