### ISSUE TITLE
Args Member return to a 5xx.

### ISSUE THREAD

**Issue by p4rkrs** [pyraxo/sylphy#16]
Hello,

The USAGE with type member return to 500 error

![image](https://user-images.githubusercontent.com/25879000/28576906-7e66b312-7155-11e7-9f99-f25358862ba8.png)

And when I quote the `args.member.id` that return to me to an 4xx Error. That's my full code: https://github.com/itskiru/sagiri-bot/blob/master/src/commands/mod/kick.js

**Comment by p4rkrs** [comment]
Oh I forgot, that's the console.log of args.member: 
![image](https://user-images.githubusercontent.com/25879000/28577080-06e319ec-7156-11e7-96ae-5adf1ba80899.png)

But the console.log of `args.member.id` return to `undefined`.

**Comment by p4rkrs** [comment]
Anyways, the type 'member' keep undefined when we use it.

**Comment by pyraxo** [comment]
`args` will always return an array, you should be doing `args.member[0].id`
