### ISSUE TITLE
adminOnly dont work :/

### ISSUE THREAD

**Issue by p4rkrs** [pyraxo/sylphy#23]
Hey, 

the option adminOnly dont work. I set my ID (and urs xd) into the ADMIN_IDS env. But still dont respond. is like the option dont reconize the ID. 

Thanks

**Comment by pyraxo** [comment]
the framework doesn't use `.env` to get its configuration values, only the `options` object which you supply when you do `new Client()`

to supply it with admin IDs, you should add `admins: [array of admin IDs]` in your `new Client` constructor

see [docs](https://pyraxo.github.io/sylphy/Client.html)
