### ISSUE TITLE
Issue with permissions

### ISSUE THREAD

**Issue by TMUniversal** [pyraxo/sylphy#40]
I've tried making some moderation commands with your framework, but it doesn't seem to care about the permissions I set. This is how the commands file begins:
```
const { Command } = require('sylphy');

class Purge extends Command {
    constructor (...args) {
        super (...args, {
            name: 'purge',
            group: 'moderation',
            aliases: ['clear', 'delete', 'prune'],
            cooldown: 2,
            options: { guildOnly: true, requirements: { permissions: { manageMessages: true } } },
```

Am I doing it wrong or is there actually an issue?

**Comment by bit0r1n** [comment]
it takes permissions for author from `options.permissions[]` and for bot `options.botPerms[]`

**Comment by TMUniversal** [comment]
Thanks a lot. What does the array need to contain? I've tried `'MANAGE_MESSAGES'`, unsuccessfully

**Comment by bit0r1n** [comment]
eris library has other names of [permissions](https://abal.moe/Eris/docs/reference). you doing right, but you pushed to array discord.js permission name

**Comment by TMUniversal** [comment]
Got it to work. Thank you a lot!! You've been a tremendous help <3
